# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7dcdf3dacbb3b98f1f3a64ebd97bf90e8887c8acf60d7281f9deed95181b3b1b2e373370d2b4a18c1cede54e1578a7ebf72840380ab6c333335ab962f587918

test:
  secret_key_base: 7d2f7d680620632cffb1451b89cae48eec3537f6201c62c42167ea84859c898da02e51b0002d5de014dcd28236c5b6dc94c92c2a391a8193f827b5c88fd67410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
